// Package t212 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package t212

import (
	"time"
)

const (
	AuthWithSecretKeyScopes  authWithSecretKeyContextKey  = "authWithSecretKey.Scopes"
	LegacyApiKeyHeaderScopes legacyApiKeyHeaderContextKey = "legacyApiKeyHeader.Scopes"
)

// Defines values for AccountBucketDetailedResponseDividendCashAction.
const (
	AccountBucketDetailedResponseDividendCashActionREINVEST      AccountBucketDetailedResponseDividendCashAction = "REINVEST"
	AccountBucketDetailedResponseDividendCashActionTOACCOUNTCASH AccountBucketDetailedResponseDividendCashAction = "TO_ACCOUNT_CASH"
)

// Valid indicates whether the value is a known member of the AccountBucketDetailedResponseDividendCashAction enum.
func (e AccountBucketDetailedResponseDividendCashAction) Valid() bool {
	switch e {
	case AccountBucketDetailedResponseDividendCashActionREINVEST:
		return true
	case AccountBucketDetailedResponseDividendCashActionTOACCOUNTCASH:
		return true
	default:
		return false
	}
}

// Defines values for AccountBucketResultResponseStatus.
const (
	AHEAD   AccountBucketResultResponseStatus = "AHEAD"
	BEHIND  AccountBucketResultResponseStatus = "BEHIND"
	ONTRACK AccountBucketResultResponseStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the AccountBucketResultResponseStatus enum.
func (e AccountBucketResultResponseStatus) Valid() bool {
	switch e {
	case AHEAD:
		return true
	case BEHIND:
		return true
	case ONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for FillTradingMethod.
const (
	OTC  FillTradingMethod = "OTC"
	TOTV FillTradingMethod = "TOTV"
)

// Valid indicates whether the value is a known member of the FillTradingMethod enum.
func (e FillTradingMethod) Valid() bool {
	switch e {
	case OTC:
		return true
	case TOTV:
		return true
	default:
		return false
	}
}

// Defines values for FillType.
const (
	CASHANDSTOCKACQUISITION FillType = "CASH_AND_STOCK_ACQUISITION"
	CUSTOMSTOCKDISTRIBUTION FillType = "CUSTOM_STOCK_DISTRIBUTION"
	EQUITYRIGHTS            FillType = "EQUITY_RIGHTS"
	FOP                     FillType = "FOP"
	FOPCORRECTION           FillType = "FOP_CORRECTION"
	SCRIPSTOCKDIVIDENDS     FillType = "SCRIP_STOCK_DIVIDENDS"
	SPINOFF                 FillType = "SPIN_OFF"
	STOCKACQUISITION        FillType = "STOCK_ACQUISITION"
	STOCKDISTRIBUTION       FillType = "STOCK_DISTRIBUTION"
	STOCKDIVIDENDS          FillType = "STOCK_DIVIDENDS"
	STOCKSPLIT              FillType = "STOCK_SPLIT"
	TRADE                   FillType = "TRADE"
)

// Valid indicates whether the value is a known member of the FillType enum.
func (e FillType) Valid() bool {
	switch e {
	case CASHANDSTOCKACQUISITION:
		return true
	case CUSTOMSTOCKDISTRIBUTION:
		return true
	case EQUITYRIGHTS:
		return true
	case FOP:
		return true
	case FOPCORRECTION:
		return true
	case SCRIPSTOCKDIVIDENDS:
		return true
	case SPINOFF:
		return true
	case STOCKACQUISITION:
		return true
	case STOCKDISTRIBUTION:
		return true
	case STOCKDIVIDENDS:
		return true
	case STOCKSPLIT:
		return true
	case TRADE:
		return true
	default:
		return false
	}
}

// Defines values for HistoryDividendItemType.
const (
	BONUS                                                             HistoryDividendItemType = "BONUS"
	BONUSMANUFACTUREDPAYMENT                                          HistoryDividendItemType = "BONUS_MANUFACTURED_PAYMENT"
	CAPITALGAINS                                                      HistoryDividendItemType = "CAPITAL_GAINS"
	CAPITALGAINSDISTRIBUTION                                          HistoryDividendItemType = "CAPITAL_GAINS_DISTRIBUTION"
	CAPITALGAINSDISTRIBUTIONMANUFACTUREDPAYMENT                       HistoryDividendItemType = "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT"
	CAPITALGAINSDISTRIBUTIONNONUS                                     HistoryDividendItemType = "CAPITAL_GAINS_DISTRIBUTION_NON_US"
	CAPITALGAINSDISTRIBUTIONNONUSMANUFACTUREDPAYMENT                  HistoryDividendItemType = "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT"
	CAPITALGAINSMANUFACTUREDPAYMENT                                   HistoryDividendItemType = "CAPITAL_GAINS_MANUFACTURED_PAYMENT"
	DEMERGER                                                          HistoryDividendItemType = "DEMERGER"
	DEMERGERMANUFACTUREDPAYMENT                                       HistoryDividendItemType = "DEMERGER_MANUFACTURED_PAYMENT"
	DIVIDEND                                                          HistoryDividendItemType = "DIVIDEND"
	DIVIDENDMANUFACTUREDPAYMENT                                       HistoryDividendItemType = "DIVIDEND_MANUFACTURED_PAYMENT"
	DIVIDENDSPAIDBYFOREIGNCORPORATIONS                                HistoryDividendItemType = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS"
	DIVIDENDSPAIDBYFOREIGNCORPORATIONSMANUFACTUREDPAYMENT             HistoryDividendItemType = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
	DIVIDENDSPAIDBYUSCORPORATIONS                                     HistoryDividendItemType = "DIVIDENDS_PAID_BY_US_CORPORATIONS"
	DIVIDENDSPAIDBYUSCORPORATIONSMANUFACTUREDPAYMENT                  HistoryDividendItemType = "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT"
	INTEREST                                                          HistoryDividendItemType = "INTEREST"
	INTERESTMANUFACTUREDPAYMENT                                       HistoryDividendItemType = "INTEREST_MANUFACTURED_PAYMENT"
	INTERESTPAIDBYFOREIGNCORPORATIONS                                 HistoryDividendItemType = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS"
	INTERESTPAIDBYFOREIGNCORPORATIONSMANUFACTUREDPAYMENT              HistoryDividendItemType = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
	INTERESTPAIDBYUSOBLIGORS                                          HistoryDividendItemType = "INTEREST_PAID_BY_US_OBLIGORS"
	INTERESTPAIDBYUSOBLIGORSMANUFACTUREDPAYMENT                       HistoryDividendItemType = "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT"
	INTERIMLIQUIDATION                                                HistoryDividendItemType = "INTERIM_LIQUIDATION"
	INTERIMLIQUIDATIONMANUFACTUREDPAYMENT                             HistoryDividendItemType = "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT"
	LONGTERMCAPITALGAINS                                              HistoryDividendItemType = "LONG_TERM_CAPITAL_GAINS"
	LONGTERMCAPITALGAINSMANUFACTUREDPAYMENT                           HistoryDividendItemType = "LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
	MULTIPLE1042STAXCOMPONENTS                                        HistoryDividendItemType = "MULTIPLE_1042S_TAX_COMPONENTS"
	MULTIPLE1042STAXCOMPONENTSMANUFACTUREDPAYMENT                     HistoryDividendItemType = "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT"
	ORDINARY                                                          HistoryDividendItemType = "ORDINARY"
	ORDINARYMANUFACTUREDPAYMENT                                       HistoryDividendItemType = "ORDINARY_MANUFACTURED_PAYMENT"
	OTHERDIVIDENDEQUIVALENT                                           HistoryDividendItemType = "OTHER_DIVIDEND_EQUIVALENT"
	OTHERDIVIDENDEQUIVALENTMANUFACTUREDPAYMENT                        HistoryDividendItemType = "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT"
	OTHERINCOME                                                       HistoryDividendItemType = "OTHER_INCOME"
	OTHERINCOMEMANUFACTUREDPAYMENT                                    HistoryDividendItemType = "OTHER_INCOME_MANUFACTURED_PAYMENT"
	PROPERTYINCOME                                                    HistoryDividendItemType = "PROPERTY_INCOME"
	PROPERTYINCOMEDISTRIBUTION                                        HistoryDividendItemType = "PROPERTY_INCOME_DISTRIBUTION"
	PROPERTYINCOMEDISTRIBUTIONMANUFACTUREDPAYMENT                     HistoryDividendItemType = "PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT"
	PROPERTYINCOMEMANUFACTUREDPAYMENT                                 HistoryDividendItemType = "PROPERTY_INCOME_MANUFACTURED_PAYMENT"
	PTPUNCHARACTERISEDINCOME                                          HistoryDividendItemType = "PTP_UNCHARACTERISED_INCOME"
	PTPUNCHARACTERISEDINCOMEMANUFACTUREDPAYMENT                       HistoryDividendItemType = "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT"
	PUBLICLYTRADEDPARTNERSHIPDISTRIBUTION                             HistoryDividendItemType = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION"
	PUBLICLYTRADEDPARTNERSHIPDISTRIBUTIONMANUFACTUREDPAYMENT          HistoryDividendItemType = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT"
	QUALIFIEDINVESTMENTENTITY                                         HistoryDividendItemType = "QUALIFIED_INVESTMENT_ENTITY"
	QUALIFIEDINVESTMENTENTITYMANUFACTUREDPAYMENT                      HistoryDividendItemType = "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT"
	REALPROPERTYINCOMEANDNATURALRESOURCESROYALTIES                    HistoryDividendItemType = "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES"
	REALPROPERTYINCOMEANDNATURALRESOURCESROYALTIESMANUFACTUREDPAYMENT HistoryDividendItemType = "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT"
	RETURNOFCAPITAL                                                   HistoryDividendItemType = "RETURN_OF_CAPITAL"
	RETURNOFCAPITALMANUFACTUREDPAYMENT                                HistoryDividendItemType = "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT"
	RETURNOFCAPITALNONUS                                              HistoryDividendItemType = "RETURN_OF_CAPITAL_NON_US"
	RETURNOFCAPITALNONUSMANUFACTUREDPAYMENT                           HistoryDividendItemType = "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT"
	SHORTTERMCAPITALGAINS                                             HistoryDividendItemType = "SHORT_TERM_CAPITAL_GAINS"
	SHORTTERMCAPITALGAINSMANUFACTUREDPAYMENT                          HistoryDividendItemType = "SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
	TAXEVENT1446FFORPUBLICLYTRADEDSECURITIES                          HistoryDividendItemType = "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES"
	TAXEVENT1446FFORPUBLICLYTRADEDSECURITIESMANUFACTUREDPAYMENT       HistoryDividendItemType = "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT"
	TAXEXEMPTED                                                       HistoryDividendItemType = "TAX_EXEMPTED"
	TAXEXEMPTEDMANUFACTUREDPAYMENT                                    HistoryDividendItemType = "TAX_EXEMPTED_MANUFACTURED_PAYMENT"
	TRUSTDISTRIBUTION                                                 HistoryDividendItemType = "TRUST_DISTRIBUTION"
	TRUSTDISTRIBUTIONMANUFACTUREDPAYMENT                              HistoryDividendItemType = "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT"
)

// Valid indicates whether the value is a known member of the HistoryDividendItemType enum.
func (e HistoryDividendItemType) Valid() bool {
	switch e {
	case BONUS:
		return true
	case BONUSMANUFACTUREDPAYMENT:
		return true
	case CAPITALGAINS:
		return true
	case CAPITALGAINSDISTRIBUTION:
		return true
	case CAPITALGAINSDISTRIBUTIONMANUFACTUREDPAYMENT:
		return true
	case CAPITALGAINSDISTRIBUTIONNONUS:
		return true
	case CAPITALGAINSDISTRIBUTIONNONUSMANUFACTUREDPAYMENT:
		return true
	case CAPITALGAINSMANUFACTUREDPAYMENT:
		return true
	case DEMERGER:
		return true
	case DEMERGERMANUFACTUREDPAYMENT:
		return true
	case DIVIDEND:
		return true
	case DIVIDENDMANUFACTUREDPAYMENT:
		return true
	case DIVIDENDSPAIDBYFOREIGNCORPORATIONS:
		return true
	case DIVIDENDSPAIDBYFOREIGNCORPORATIONSMANUFACTUREDPAYMENT:
		return true
	case DIVIDENDSPAIDBYUSCORPORATIONS:
		return true
	case DIVIDENDSPAIDBYUSCORPORATIONSMANUFACTUREDPAYMENT:
		return true
	case INTEREST:
		return true
	case INTERESTMANUFACTUREDPAYMENT:
		return true
	case INTERESTPAIDBYFOREIGNCORPORATIONS:
		return true
	case INTERESTPAIDBYFOREIGNCORPORATIONSMANUFACTUREDPAYMENT:
		return true
	case INTERESTPAIDBYUSOBLIGORS:
		return true
	case INTERESTPAIDBYUSOBLIGORSMANUFACTUREDPAYMENT:
		return true
	case INTERIMLIQUIDATION:
		return true
	case INTERIMLIQUIDATIONMANUFACTUREDPAYMENT:
		return true
	case LONGTERMCAPITALGAINS:
		return true
	case LONGTERMCAPITALGAINSMANUFACTUREDPAYMENT:
		return true
	case MULTIPLE1042STAXCOMPONENTS:
		return true
	case MULTIPLE1042STAXCOMPONENTSMANUFACTUREDPAYMENT:
		return true
	case ORDINARY:
		return true
	case ORDINARYMANUFACTUREDPAYMENT:
		return true
	case OTHERDIVIDENDEQUIVALENT:
		return true
	case OTHERDIVIDENDEQUIVALENTMANUFACTUREDPAYMENT:
		return true
	case OTHERINCOME:
		return true
	case OTHERINCOMEMANUFACTUREDPAYMENT:
		return true
	case PROPERTYINCOME:
		return true
	case PROPERTYINCOMEDISTRIBUTION:
		return true
	case PROPERTYINCOMEDISTRIBUTIONMANUFACTUREDPAYMENT:
		return true
	case PROPERTYINCOMEMANUFACTUREDPAYMENT:
		return true
	case PTPUNCHARACTERISEDINCOME:
		return true
	case PTPUNCHARACTERISEDINCOMEMANUFACTUREDPAYMENT:
		return true
	case PUBLICLYTRADEDPARTNERSHIPDISTRIBUTION:
		return true
	case PUBLICLYTRADEDPARTNERSHIPDISTRIBUTIONMANUFACTUREDPAYMENT:
		return true
	case QUALIFIEDINVESTMENTENTITY:
		return true
	case QUALIFIEDINVESTMENTENTITYMANUFACTUREDPAYMENT:
		return true
	case REALPROPERTYINCOMEANDNATURALRESOURCESROYALTIES:
		return true
	case REALPROPERTYINCOMEANDNATURALRESOURCESROYALTIESMANUFACTUREDPAYMENT:
		return true
	case RETURNOFCAPITAL:
		return true
	case RETURNOFCAPITALMANUFACTUREDPAYMENT:
		return true
	case RETURNOFCAPITALNONUS:
		return true
	case RETURNOFCAPITALNONUSMANUFACTUREDPAYMENT:
		return true
	case SHORTTERMCAPITALGAINS:
		return true
	case SHORTTERMCAPITALGAINSMANUFACTUREDPAYMENT:
		return true
	case TAXEVENT1446FFORPUBLICLYTRADEDSECURITIES:
		return true
	case TAXEVENT1446FFORPUBLICLYTRADEDSECURITIESMANUFACTUREDPAYMENT:
		return true
	case TAXEXEMPTED:
		return true
	case TAXEXEMPTEDMANUFACTUREDPAYMENT:
		return true
	case TRUSTDISTRIBUTION:
		return true
	case TRUSTDISTRIBUTIONMANUFACTUREDPAYMENT:
		return true
	default:
		return false
	}
}

// Defines values for HistoryTransactionItemType.
const (
	DEPOSIT  HistoryTransactionItemType = "DEPOSIT"
	FEE      HistoryTransactionItemType = "FEE"
	TRANSFER HistoryTransactionItemType = "TRANSFER"
	WITHDRAW HistoryTransactionItemType = "WITHDRAW"
)

// Valid indicates whether the value is a known member of the HistoryTransactionItemType enum.
func (e HistoryTransactionItemType) Valid() bool {
	switch e {
	case DEPOSIT:
		return true
	case FEE:
		return true
	case TRANSFER:
		return true
	case WITHDRAW:
		return true
	default:
		return false
	}
}

// Defines values for InstrumentIssueName.
const (
	APPROACHINGMAXPOSITIONSIZE       InstrumentIssueName = "APPROACHING_MAX_POSITION_SIZE"
	COMPLEXINSTRUMENTAPPTESTREQUIRED InstrumentIssueName = "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED"
	DELISTED                         InstrumentIssueName = "DELISTED"
	MAXPOSITIONSIZEREACHED           InstrumentIssueName = "MAX_POSITION_SIZE_REACHED"
	NOLONGERTRADABLE                 InstrumentIssueName = "NO_LONGER_TRADABLE"
	PRICETOOLOW                      InstrumentIssueName = "PRICE_TOO_LOW"
	SUSPENDED                        InstrumentIssueName = "SUSPENDED"
)

// Valid indicates whether the value is a known member of the InstrumentIssueName enum.
func (e InstrumentIssueName) Valid() bool {
	switch e {
	case APPROACHINGMAXPOSITIONSIZE:
		return true
	case COMPLEXINSTRUMENTAPPTESTREQUIRED:
		return true
	case DELISTED:
		return true
	case MAXPOSITIONSIZEREACHED:
		return true
	case NOLONGERTRADABLE:
		return true
	case PRICETOOLOW:
		return true
	case SUSPENDED:
		return true
	default:
		return false
	}
}

// Defines values for InstrumentIssueSeverity.
const (
	INFORMATIVE  InstrumentIssueSeverity = "INFORMATIVE"
	IRREVERSIBLE InstrumentIssueSeverity = "IRREVERSIBLE"
	REVERSIBLE   InstrumentIssueSeverity = "REVERSIBLE"
)

// Valid indicates whether the value is a known member of the InstrumentIssueSeverity enum.
func (e InstrumentIssueSeverity) Valid() bool {
	switch e {
	case INFORMATIVE:
		return true
	case IRREVERSIBLE:
		return true
	case REVERSIBLE:
		return true
	default:
		return false
	}
}

// Defines values for OrderInitiatedFrom.
const (
	ANDROID    OrderInitiatedFrom = "ANDROID"
	API        OrderInitiatedFrom = "API"
	AUTOINVEST OrderInitiatedFrom = "AUTOINVEST"
	IOS        OrderInitiatedFrom = "IOS"
	SYSTEM     OrderInitiatedFrom = "SYSTEM"
	WEB        OrderInitiatedFrom = "WEB"
)

// Valid indicates whether the value is a known member of the OrderInitiatedFrom enum.
func (e OrderInitiatedFrom) Valid() bool {
	switch e {
	case ANDROID:
		return true
	case API:
		return true
	case AUTOINVEST:
		return true
	case IOS:
		return true
	case SYSTEM:
		return true
	case WEB:
		return true
	default:
		return false
	}
}

// Defines values for OrderSide.
const (
	BUY  OrderSide = "BUY"
	SELL OrderSide = "SELL"
)

// Valid indicates whether the value is a known member of the OrderSide enum.
func (e OrderSide) Valid() bool {
	switch e {
	case BUY:
		return true
	case SELL:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	CANCELLED       OrderStatus = "CANCELLED"
	CANCELLING      OrderStatus = "CANCELLING"
	CONFIRMED       OrderStatus = "CONFIRMED"
	FILLED          OrderStatus = "FILLED"
	LOCAL           OrderStatus = "LOCAL"
	NEW             OrderStatus = "NEW"
	PARTIALLYFILLED OrderStatus = "PARTIALLY_FILLED"
	REJECTED        OrderStatus = "REJECTED"
	REPLACED        OrderStatus = "REPLACED"
	REPLACING       OrderStatus = "REPLACING"
	UNCONFIRMED     OrderStatus = "UNCONFIRMED"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case CANCELLED:
		return true
	case CANCELLING:
		return true
	case CONFIRMED:
		return true
	case FILLED:
		return true
	case LOCAL:
		return true
	case NEW:
		return true
	case PARTIALLYFILLED:
		return true
	case REJECTED:
		return true
	case REPLACED:
		return true
	case REPLACING:
		return true
	case UNCONFIRMED:
		return true
	default:
		return false
	}
}

// Defines values for OrderStrategy.
const (
	QUANTITY OrderStrategy = "QUANTITY"
	VALUE    OrderStrategy = "VALUE"
)

// Valid indicates whether the value is a known member of the OrderStrategy enum.
func (e OrderStrategy) Valid() bool {
	switch e {
	case QUANTITY:
		return true
	case VALUE:
		return true
	default:
		return false
	}
}

// Defines values for OrderType.
const (
	LIMIT     OrderType = "LIMIT"
	MARKET    OrderType = "MARKET"
	STOP      OrderType = "STOP"
	STOPLIMIT OrderType = "STOP_LIMIT"
)

// Valid indicates whether the value is a known member of the OrderType enum.
func (e OrderType) Valid() bool {
	switch e {
	case LIMIT:
		return true
	case MARKET:
		return true
	case STOP:
		return true
	case STOPLIMIT:
		return true
	default:
		return false
	}
}

// Defines values for PieRequestDividendCashAction.
const (
	PieRequestDividendCashActionREINVEST      PieRequestDividendCashAction = "REINVEST"
	PieRequestDividendCashActionTOACCOUNTCASH PieRequestDividendCashAction = "TO_ACCOUNT_CASH"
)

// Valid indicates whether the value is a known member of the PieRequestDividendCashAction enum.
func (e PieRequestDividendCashAction) Valid() bool {
	switch e {
	case PieRequestDividendCashActionREINVEST:
		return true
	case PieRequestDividendCashActionTOACCOUNTCASH:
		return true
	default:
		return false
	}
}

// Defines values for ReportResponseStatus.
const (
	Canceled   ReportResponseStatus = "Canceled"
	Failed     ReportResponseStatus = "Failed"
	Finished   ReportResponseStatus = "Finished"
	Processing ReportResponseStatus = "Processing"
	Queued     ReportResponseStatus = "Queued"
	Running    ReportResponseStatus = "Running"
)

// Valid indicates whether the value is a known member of the ReportResponseStatus enum.
func (e ReportResponseStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Finished:
		return true
	case Processing:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for TaxName.
const (
	COMMISSIONTURNOVER    TaxName = "COMMISSION_TURNOVER"
	CURRENCYCONVERSIONFEE TaxName = "CURRENCY_CONVERSION_FEE"
	FINRAFEE              TaxName = "FINRA_FEE"
	FRENCHTRANSACTIONTAX  TaxName = "FRENCH_TRANSACTION_TAX"
	PTMLEVY               TaxName = "PTM_LEVY"
	STAMPDUTY             TaxName = "STAMP_DUTY"
	STAMPDUTYRESERVETAX   TaxName = "STAMP_DUTY_RESERVE_TAX"
	TRANSACTIONFEE        TaxName = "TRANSACTION_FEE"
)

// Valid indicates whether the value is a known member of the TaxName enum.
func (e TaxName) Valid() bool {
	switch e {
	case COMMISSIONTURNOVER:
		return true
	case CURRENCYCONVERSIONFEE:
		return true
	case FINRAFEE:
		return true
	case FRENCHTRANSACTIONTAX:
		return true
	case PTMLEVY:
		return true
	case STAMPDUTY:
		return true
	case STAMPDUTYRESERVETAX:
		return true
	case TRANSACTIONFEE:
		return true
	default:
		return false
	}
}

// Defines values for TimeEventType.
const (
	AFTERHOURSCLOSE TimeEventType = "AFTER_HOURS_CLOSE"
	AFTERHOURSOPEN  TimeEventType = "AFTER_HOURS_OPEN"
	BREAKEND        TimeEventType = "BREAK_END"
	BREAKSTART      TimeEventType = "BREAK_START"
	CLOSE           TimeEventType = "CLOSE"
	OPEN            TimeEventType = "OPEN"
	OVERNIGHTOPEN   TimeEventType = "OVERNIGHT_OPEN"
	PREMARKETOPEN   TimeEventType = "PRE_MARKET_OPEN"
)

// Valid indicates whether the value is a known member of the TimeEventType enum.
func (e TimeEventType) Valid() bool {
	switch e {
	case AFTERHOURSCLOSE:
		return true
	case AFTERHOURSOPEN:
		return true
	case BREAKEND:
		return true
	case BREAKSTART:
		return true
	case CLOSE:
		return true
	case OPEN:
		return true
	case OVERNIGHTOPEN:
		return true
	case PREMARKETOPEN:
		return true
	default:
		return false
	}
}

// Defines values for TimeValidity.
const (
	DAY            TimeValidity = "DAY"
	GOODTILLCANCEL TimeValidity = "GOOD_TILL_CANCEL"
)

// Valid indicates whether the value is a known member of the TimeValidity enum.
func (e TimeValidity) Valid() bool {
	switch e {
	case DAY:
		return true
	case GOODTILLCANCEL:
		return true
	default:
		return false
	}
}

// Defines values for TradableInstrumentType.
const (
	CORPACT        TradableInstrumentType = "CORPACT"
	CRYPTO         TradableInstrumentType = "CRYPTO"
	CRYPTOCURRENCY TradableInstrumentType = "CRYPTOCURRENCY"
	CVR            TradableInstrumentType = "CVR"
	ETF            TradableInstrumentType = "ETF"
	FOREX          TradableInstrumentType = "FOREX"
	FUTURES        TradableInstrumentType = "FUTURES"
	INDEX          TradableInstrumentType = "INDEX"
	STOCK          TradableInstrumentType = "STOCK"
	WARRANT        TradableInstrumentType = "WARRANT"
)

// Valid indicates whether the value is a known member of the TradableInstrumentType enum.
func (e TradableInstrumentType) Valid() bool {
	switch e {
	case CORPACT:
		return true
	case CRYPTO:
		return true
	case CRYPTOCURRENCY:
		return true
	case CVR:
		return true
	case ETF:
		return true
	case FOREX:
		return true
	case FUTURES:
		return true
	case INDEX:
		return true
	case STOCK:
		return true
	case WARRANT:
		return true
	default:
		return false
	}
}

// AccountBucketDetailedResponse defines model for AccountBucketDetailedResponse.
type AccountBucketDetailedResponse struct {
	CreationDate       *time.Time                                       `json:"creationDate,omitempty"`
	DividendCashAction *AccountBucketDetailedResponseDividendCashAction `json:"dividendCashAction,omitempty"`
	EndDate            *time.Time                                       `json:"endDate,omitempty"`
	Goal               *float32                                         `json:"goal,omitempty"`
	Icon               *string                                          `json:"icon,omitempty"`
	Id                 *int64                                           `json:"id,omitempty"`
	InitialInvestment  *float32                                         `json:"initialInvestment,omitempty"`
	InstrumentShares   *map[string]float32                              `json:"instrumentShares,omitempty"`
	Name               *string                                          `json:"name,omitempty"`
	PublicUrl          *string                                          `json:"publicUrl,omitempty"`
}

// AccountBucketDetailedResponseDividendCashAction defines model for AccountBucketDetailedResponse.DividendCashAction.
type AccountBucketDetailedResponseDividendCashAction string

// AccountBucketInstrumentResult defines model for AccountBucketInstrumentResult.
type AccountBucketInstrumentResult struct {
	CurrentShare  *float32           `json:"currentShare,omitempty"`
	ExpectedShare *float32           `json:"expectedShare,omitempty"`
	Issues        *[]InstrumentIssue `json:"issues,omitempty"`
	OwnedQuantity *float32           `json:"ownedQuantity,omitempty"`
	Result        *InvestmentResult  `json:"result,omitempty"`
	Ticker        *string            `json:"ticker,omitempty"`
}

// AccountBucketInstrumentsDetailedResponse defines model for AccountBucketInstrumentsDetailedResponse.
type AccountBucketInstrumentsDetailedResponse struct {
	Instruments *[]AccountBucketInstrumentResult `json:"instruments,omitempty"`
	Settings    *AccountBucketDetailedResponse   `json:"settings,omitempty"`
}

// AccountBucketResultResponse defines model for AccountBucketResultResponse.
type AccountBucketResultResponse struct {
	// Cash Amount of money put into the pie in account currency
	Cash            *float32         `json:"cash,omitempty"`
	DividendDetails *DividendDetails `json:"dividendDetails,omitempty"`
	Id              *int64           `json:"id,omitempty"`

	// Progress Progress of the pie based on the set goal
	Progress *float32          `json:"progress,omitempty"`
	Result   *InvestmentResult `json:"result,omitempty"`

	// Status Status of the pie based on the set goal
	Status *AccountBucketResultResponseStatus `json:"status,omitempty"`
}

// AccountBucketResultResponseStatus Status of the pie based on the set goal
type AccountBucketResultResponseStatus string

// AccountSummary defines model for AccountSummary.
type AccountSummary struct {
	Cash *Cash `json:"cash,omitempty"`

	// Currency Primary account currency in ISO 4217 format.
	Currency *string `json:"currency,omitempty"`

	// Id Primary trading account number. This is the same account ID you would see in the Trading 212 web or mobile application.
	Id          *int64       `json:"id,omitempty"`
	Investments *Investments `json:"investments,omitempty"`

	// TotalValue Investments value in your account's primary currency.
	TotalValue *float32 `json:"totalValue,omitempty"`
}

// Cash defines model for Cash.
type Cash struct {
	// AvailableToTrade Funds available for investing.
	AvailableToTrade *float32 `json:"availableToTrade,omitempty"`

	// InPies It’s the sum of the cash inside of all pies that is not yet invested.
	InPies *float32 `json:"inPies,omitempty"`

	// ReservedForOrders The amount of cash reserved for pending orders. This cash is not available for placing new trades.
	ReservedForOrders *float32 `json:"reservedForOrders,omitempty"`
}

// DividendDetails defines model for DividendDetails.
type DividendDetails struct {
	Gained     *float32 `json:"gained,omitempty"`
	InCash     *float32 `json:"inCash,omitempty"`
	Reinvested *float32 `json:"reinvested,omitempty"`
}

// DuplicateBucketRequest defines model for DuplicateBucketRequest.
type DuplicateBucketRequest struct {
	Icon *string `json:"icon,omitempty"`
	Name *string `json:"name,omitempty"`
}

// EnqueuedReportResponse defines model for EnqueuedReportResponse.
type EnqueuedReportResponse struct {
	ReportId *int64 `json:"reportId,omitempty"`
}

// Exchange defines model for Exchange.
type Exchange struct {
	Id               *int64             `json:"id,omitempty"`
	Name             *string            `json:"name,omitempty"`
	WorkingSchedules *[]WorkingSchedule `json:"workingSchedules,omitempty"`
}

// Fill defines model for Fill.
type Fill struct {
	FilledAt      *time.Time         `json:"filledAt,omitempty"`
	Id            *int64             `json:"id,omitempty"`
	Price         *float32           `json:"price,omitempty"`
	Quantity      *float32           `json:"quantity,omitempty"`
	TradingMethod *FillTradingMethod `json:"tradingMethod,omitempty"`
	Type          *FillType          `json:"type,omitempty"`
	WalletImpact  *FillWalletImpact  `json:"walletImpact,omitempty"`
}

// FillTradingMethod defines model for Fill.TradingMethod.
type FillTradingMethod string

// FillType defines model for Fill.Type.
type FillType string

// FillWalletImpact defines model for FillWalletImpact.
type FillWalletImpact struct {
	Currency           *string  `json:"currency,omitempty"`
	FxRate             *float32 `json:"fxRate,omitempty"`
	NetValue           *float32 `json:"netValue,omitempty"`
	RealisedProfitLoss *float32 `json:"realisedProfitLoss,omitempty"`
	Taxes              *[]Tax   `json:"taxes,omitempty"`
}

// HistoricalOrder defines model for HistoricalOrder.
type HistoricalOrder struct {
	Fill  *Fill  `json:"fill,omitempty"`
	Order *Order `json:"order,omitempty"`
}

// HistoryDividendItem defines model for HistoryDividendItem.
type HistoryDividendItem struct {
	// Amount In account's primary currency.
	Amount       *float32 `json:"amount,omitempty"`
	AmountInEuro *float32 `json:"amountInEuro,omitempty"`

	// Currency The account's primary currency.
	Currency *string `json:"currency,omitempty"`

	// GrossAmountPerShare In instrument currency
	GrossAmountPerShare *float32 `json:"grossAmountPerShare,omitempty"`

	// Instrument Instrument information as given by /instruments endpoint.
	Instrument     *Instrument              `json:"instrument,omitempty"`
	PaidOn         *time.Time               `json:"paidOn,omitempty"`
	Quantity       *float32                 `json:"quantity,omitempty"`
	Reference      *string                  `json:"reference,omitempty"`
	Ticker         *string                  `json:"ticker,omitempty"`
	TickerCurrency *string                  `json:"tickerCurrency,omitempty"`
	Type           *HistoryDividendItemType `json:"type,omitempty"`
}

// HistoryDividendItemType defines model for HistoryDividendItem.Type.
type HistoryDividendItemType string

// HistoryTransactionItem defines model for HistoryTransactionItem.
type HistoryTransactionItem struct {
	// Amount Amount in the currency of the transaction
	Amount *float32 `json:"amount,omitempty"`

	// Currency Currency of the transaction
	Currency *string    `json:"currency,omitempty"`
	DateTime *time.Time `json:"dateTime,omitempty"`

	// Reference ID
	Reference *string                     `json:"reference,omitempty"`
	Type      *HistoryTransactionItemType `json:"type,omitempty"`
}

// HistoryTransactionItemType defines model for HistoryTransactionItem.Type.
type HistoryTransactionItemType string

// Instrument Instrument information as given by /instruments endpoint.
type Instrument struct {
	// Currency Instrument currency in ISO 4217 format.
	Currency *string `json:"currency,omitempty"`

	// Isin ISIN of the instrument.
	Isin *string `json:"isin,omitempty"`

	// Name Name of the instrument.
	Name *string `json:"name,omitempty"`

	// Ticker Unique instrument identifier.
	Ticker *string `json:"ticker,omitempty"`
}

// InstrumentIssue defines model for InstrumentIssue.
type InstrumentIssue struct {
	Name     *InstrumentIssueName     `json:"name,omitempty"`
	Severity *InstrumentIssueSeverity `json:"severity,omitempty"`
}

// InstrumentIssueName defines model for InstrumentIssue.Name.
type InstrumentIssueName string

// InstrumentIssueSeverity defines model for InstrumentIssue.Severity.
type InstrumentIssueSeverity string

// InvestmentResult defines model for InvestmentResult.
type InvestmentResult struct {
	PriceAvgInvestedValue *float32 `json:"priceAvgInvestedValue,omitempty"`
	PriceAvgResult        *float32 `json:"priceAvgResult,omitempty"`
	PriceAvgResultCoef    *float32 `json:"priceAvgResultCoef,omitempty"`
	PriceAvgValue         *float32 `json:"priceAvgValue,omitempty"`
}

// Investments defines model for Investments.
type Investments struct {
	// CurrentValue Current value of all the investments.
	CurrentValue *float32 `json:"currentValue,omitempty"`

	// RealizedProfitLoss The all-time realised profit loss from all of the trades executed.
	RealizedProfitLoss *float32 `json:"realizedProfitLoss,omitempty"`

	// TotalCost The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own.
	TotalCost *float32 `json:"totalCost,omitempty"`

	// UnrealizedProfitLoss The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now.
	UnrealizedProfitLoss *float32 `json:"unrealizedProfitLoss,omitempty"`
}

// LimitRequest defines model for LimitRequest.
type LimitRequest struct {
	LimitPrice *float32 `json:"limitPrice,omitempty"`
	Quantity   *float32 `json:"quantity,omitempty"`
	Ticker     *string  `json:"ticker,omitempty"`

	// TimeValidity Specifies how long the order remains active:
	// * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
	// * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
	TimeValidity *TimeValidity `json:"timeValidity,omitempty"`
}

// MarketRequest defines model for MarketRequest.
type MarketRequest struct {
	ExtendedHours *bool    `json:"extendedHours,omitempty"`
	Quantity      *float32 `json:"quantity,omitempty"`
	Ticker        *string  `json:"ticker,omitempty"`
}

// Order defines model for Order.
type Order struct {
	// CreatedAt The ISO 8601 formatted date of when the order was created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Currency The currency used for the order in ISO 4217 format.
	Currency *string `json:"currency,omitempty"`

	// ExtendedHours If true, the order is eligible for execution outside regular trading hours.
	ExtendedHours *bool `json:"extendedHours,omitempty"`

	// FilledQuantity The number of shares that have been successfully executed. Applicable to quantity orders.
	FilledQuantity *float32 `json:"filledQuantity,omitempty"`

	// FilledValue The total monetary value of the executed portion of the order. Applicable  to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms.
	FilledValue *float32 `json:"filledValue,omitempty"`

	// Id A unique, system-generated identifier for the order.
	Id *int64 `json:"id,omitempty"`

	// InitiatedFrom How the order was initiated.
	InitiatedFrom *OrderInitiatedFrom `json:"initiatedFrom,omitempty"`

	// Instrument Instrument information as given by /instruments endpoint.
	Instrument *Instrument `json:"instrument,omitempty"`

	// LimitPrice Applicable to LIMIT and STOP_LIMIT orders.
	LimitPrice *float32 `json:"limitPrice,omitempty"`

	// Quantity The total number of shares requested. Applicable to quantity orders.
	Quantity *float32 `json:"quantity,omitempty"`

	// Side Indicates whether the order is BUY or SELL.
	Side *OrderSide `json:"side,omitempty"`

	// Status The current state of the order in its lifecycle.
	Status *OrderStatus `json:"status,omitempty"`

	// StopPrice Applicable to STOP and STOP_LIMIT orders.
	StopPrice *float32 `json:"stopPrice,omitempty"`

	// Strategy The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY.
	Strategy *OrderStrategy `json:"strategy,omitempty"`

	// Ticker Unique instrument identifier. Get from the /instruments endpoint
	Ticker *string `json:"ticker,omitempty"`

	// TimeInForce Specifies how long the order remains active:
	// * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
	// * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
	TimeInForce *TimeValidity `json:"timeInForce,omitempty"`
	Type        *OrderType    `json:"type,omitempty"`

	// Value The total monetary value of the order. Applicable to value orders.
	Value *float32 `json:"value,omitempty"`
}

// OrderInitiatedFrom How the order was initiated.
type OrderInitiatedFrom string

// OrderSide Indicates whether the order is BUY or SELL.
type OrderSide string

// OrderStatus The current state of the order in its lifecycle.
type OrderStatus string

// OrderStrategy The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY.
type OrderStrategy string

// OrderType defines model for Order.Type.
type OrderType string

// PaginatedResponseHistoricalOrder defines model for PaginatedResponseHistoricalOrder.
type PaginatedResponseHistoricalOrder struct {
	Items        *[]HistoricalOrder `json:"items,omitempty"`
	NextPagePath *string            `json:"nextPagePath,omitempty"`
}

// PaginatedResponseHistoryDividendItem defines model for PaginatedResponseHistoryDividendItem.
type PaginatedResponseHistoryDividendItem struct {
	Items        *[]HistoryDividendItem `json:"items,omitempty"`
	NextPagePath *string                `json:"nextPagePath,omitempty"`
}

// PaginatedResponseHistoryTransactionItem defines model for PaginatedResponseHistoryTransactionItem.
type PaginatedResponseHistoryTransactionItem struct {
	Items        *[]HistoryTransactionItem `json:"items,omitempty"`
	NextPagePath *string                   `json:"nextPagePath,omitempty"`
}

// PieRequest defines model for PieRequest.
type PieRequest struct {
	DividendCashAction *PieRequestDividendCashAction `json:"dividendCashAction,omitempty"`
	EndDate            *time.Time                    `json:"endDate,omitempty"`

	// Goal Total desired value of the pie in account currency
	Goal             *float32            `json:"goal,omitempty"`
	Icon             *string             `json:"icon,omitempty"`
	InstrumentShares *map[string]float32 `json:"instrumentShares,omitempty"`
	Name             *string             `json:"name,omitempty"`
}

// PieRequestDividendCashAction defines model for PieRequest.DividendCashAction.
type PieRequestDividendCashAction string

// Position defines model for Position.
type Position struct {
	// AveragePricePaid Average price paid, in instrument currency, per share.
	AveragePricePaid *float32 `json:"averagePricePaid,omitempty"`

	// CreatedAt The ISO 8601 formatted date of when the position was opened.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// CurrentPrice Current price, in instrument currency, of a single share.
	CurrentPrice *float32 `json:"currentPrice,omitempty"`

	// Instrument Instrument information as given by /instruments endpoint.
	Instrument *Instrument `json:"instrument,omitempty"`

	// Quantity Total quantity of shares owned.
	Quantity *float32 `json:"quantity,omitempty"`

	// QuantityAvailableForTrading Quantity of shares available for trading.
	QuantityAvailableForTrading *float32 `json:"quantityAvailableForTrading,omitempty"`

	// QuantityInPies Quantity of shares currently used in pie.
	QuantityInPies *float32              `json:"quantityInPies,omitempty"`
	WalletImpact   *PositionWalletImpact `json:"walletImpact,omitempty"`
}

// PositionWalletImpact defines model for PositionWalletImpact.
type PositionWalletImpact struct {
	// Currency The currency code used to represent all the wallet impact information.
	Currency *string `json:"currency,omitempty"`

	// CurrentValue The current market value of the position.
	CurrentValue *float32 `json:"currentValue,omitempty"`

	// FxImpact The positive or negative impact on the position's value due to currency rate changes.
	FxImpact *float32 `json:"fxImpact,omitempty"`

	// TotalCost The total cost paid for the position.
	TotalCost *float32 `json:"totalCost,omitempty"`

	// UnrealizedProfitLoss The unrealized profit & loss for the position. Calculated as currentValue - totalCost.
	UnrealizedProfitLoss *float32 `json:"unrealizedProfitLoss,omitempty"`
}

// PublicReportRequest defines model for PublicReportRequest.
type PublicReportRequest struct {
	DataIncluded *ReportDataIncluded `json:"dataIncluded,omitempty"`
	TimeFrom     *time.Time          `json:"timeFrom,omitempty"`
	TimeTo       *time.Time          `json:"timeTo,omitempty"`
}

// ReportDataIncluded defines model for ReportDataIncluded.
type ReportDataIncluded struct {
	IncludeDividends    *bool `json:"includeDividends,omitempty"`
	IncludeInterest     *bool `json:"includeInterest,omitempty"`
	IncludeOrders       *bool `json:"includeOrders,omitempty"`
	IncludeTransactions *bool `json:"includeTransactions,omitempty"`
}

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	DataIncluded *ReportDataIncluded   `json:"dataIncluded,omitempty"`
	DownloadLink *string               `json:"downloadLink,omitempty"`
	ReportId     *int64                `json:"reportId,omitempty"`
	Status       *ReportResponseStatus `json:"status,omitempty"`
	TimeFrom     *time.Time            `json:"timeFrom,omitempty"`
	TimeTo       *time.Time            `json:"timeTo,omitempty"`
}

// ReportResponseStatus defines model for ReportResponse.Status.
type ReportResponseStatus string

// StopLimitRequest defines model for StopLimitRequest.
type StopLimitRequest struct {
	LimitPrice *float32 `json:"limitPrice,omitempty"`
	Quantity   *float32 `json:"quantity,omitempty"`
	StopPrice  *float32 `json:"stopPrice,omitempty"`
	Ticker     *string  `json:"ticker,omitempty"`

	// TimeValidity Specifies how long the order remains active:
	// * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
	// * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
	TimeValidity *TimeValidity `json:"timeValidity,omitempty"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	Quantity  *float32 `json:"quantity,omitempty"`
	StopPrice *float32 `json:"stopPrice,omitempty"`
	Ticker    *string  `json:"ticker,omitempty"`

	// TimeValidity Specifies how long the order remains active:
	// * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
	// * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
	TimeValidity *TimeValidity `json:"timeValidity,omitempty"`
}

// Tax defines model for Tax.
type Tax struct {
	ChargedAt *time.Time `json:"chargedAt,omitempty"`
	Currency  *string    `json:"currency,omitempty"`
	Name      *TaxName   `json:"name,omitempty"`
	Quantity  *float32   `json:"quantity,omitempty"`
}

// TaxName defines model for Tax.Name.
type TaxName string

// TimeEvent defines model for TimeEvent.
type TimeEvent struct {
	Date *time.Time     `json:"date,omitempty"`
	Type *TimeEventType `json:"type,omitempty"`
}

// TimeEventType defines model for TimeEvent.Type.
type TimeEventType string

// TimeValidity Specifies how long the order remains active:
// * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
// * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
type TimeValidity string

// TradableInstrument defines model for TradableInstrument.
type TradableInstrument struct {
	// AddedOn On the platform since
	AddedOn *time.Time `json:"addedOn,omitempty"`

	// CurrencyCode ISO 4217
	CurrencyCode    *string  `json:"currencyCode,omitempty"`
	ExtendedHours   *bool    `json:"extendedHours,omitempty"`
	Isin            *string  `json:"isin,omitempty"`
	MaxOpenQuantity *float32 `json:"maxOpenQuantity,omitempty"`
	Name            *string  `json:"name,omitempty"`
	ShortName       *string  `json:"shortName,omitempty"`

	// Ticker Unique identifier
	Ticker *string                 `json:"ticker,omitempty"`
	Type   *TradableInstrumentType `json:"type,omitempty"`

	// WorkingScheduleId Get items in the /exchanges endpoint
	WorkingScheduleId *int64 `json:"workingScheduleId,omitempty"`
}

// TradableInstrumentType defines model for TradableInstrument.Type.
type TradableInstrumentType string

// WorkingSchedule defines model for WorkingSchedule.
type WorkingSchedule struct {
	Id         *int64       `json:"id,omitempty"`
	TimeEvents *[]TimeEvent `json:"timeEvents,omitempty"`
}

// authWithSecretKeyContextKey is the context key for authWithSecretKey security scheme
type authWithSecretKeyContextKey string

// legacyApiKeyHeaderContextKey is the context key for legacyApiKeyHeader security scheme
type legacyApiKeyHeaderContextKey string

// DividendsParams defines parameters for Dividends.
type DividendsParams struct {
	// Cursor Pagination cursor
	Cursor *int64 `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Ticker Ticker filter
	Ticker *string `form:"ticker,omitempty" json:"ticker,omitempty"`

	// Limit Max items: 50
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// Orders1Params defines parameters for Orders1.
type Orders1Params struct {
	// Cursor Pagination cursor
	Cursor *int64 `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Ticker Ticker filter
	Ticker *string `form:"ticker,omitempty" json:"ticker,omitempty"`

	// Limit Max items: 50
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// TransactionsParams defines parameters for Transactions.
type TransactionsParams struct {
	// Cursor Pagination cursor
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Time Retrieve transactions starting from the specified time
	Time *time.Time `form:"time,omitempty" json:"time,omitempty"`

	// Limit Max items: 50
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPositionsParams defines parameters for GetPositions.
type GetPositionsParams struct {
	Ticker *string `form:"ticker,omitempty" json:"ticker,omitempty"`
}

// RequestReportJSONRequestBody defines body for RequestReport for application/json ContentType.
type RequestReportJSONRequestBody = PublicReportRequest

// PlaceLimitOrderJSONRequestBody defines body for PlaceLimitOrder for application/json ContentType.
type PlaceLimitOrderJSONRequestBody = LimitRequest

// PlaceMarketOrderJSONRequestBody defines body for PlaceMarketOrder for application/json ContentType.
type PlaceMarketOrderJSONRequestBody = MarketRequest

// PlaceStopOrder1JSONRequestBody defines body for PlaceStopOrder1 for application/json ContentType.
type PlaceStopOrder1JSONRequestBody = StopRequest

// PlaceStopOrderJSONRequestBody defines body for PlaceStopOrder for application/json ContentType.
type PlaceStopOrderJSONRequestBody = StopLimitRequest

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = PieRequest

// UpdateJSONRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody = PieRequest

// DuplicatePieJSONRequestBody defines body for DuplicatePie for application/json ContentType.
type DuplicatePieJSONRequestBody = DuplicateBucketRequest
